INSERT INTO RESPONSAVEL(NAME, RENDA) VALUES ('ME', 2000);
INSERT INTO RESPONSAVEL(NAME, RENDA) VALUES ('CONTRATA', 2000);

INSERT INTO FAMILIA(RESPONSAVEL_ID, RESPONSAVEL2_ID, TOTAL_RENDA, TOTAL_PONTOS) VALUES (1, 2, 100, 0);

INSERT INTO DEPEDENTE(NAME, IDADE, RENDA, FAMILIA_ID) VALUES ('DIGIX', 20, 100, 1);